### ISSUE TITLE
Is there a version for Dot Net Core?

### ISSUE THREAD

**Issue by ibondy** [grumpydev/TinyIoC#103] opened 2016-08-19 15:44 UTC
Is there a version which can be used with Dot Net Core?

**Comment by malachib** [comment] 2016-08-19 21:48
Possible duplicate of #94 and #98

**Comment by niemyjski** [comment] 2018-04-10 16:50
Yes, #master currently works with .net standard 1.2 and up

**Closed by niemyjski** 2018-04-10 16:50 UTC
