### ISSUE TITLE
TinyIoC namespace cannot be found

### ISSUE THREAD

**Issue by alexrainman** [grumpydev/TinyIoC#146] opened 2021-04-14 17:46 UTC
I installed latest package on a .Net Standard library shared in a Xamarin.Forms project but, TinyIoC namespace cannot be found. Any ideas?

**Comment by niemyjski** [comment] 2021-04-15 00:51
This is a duplicate of https://github.com/grumpydev/TinyIoC/issues/136. I could use some help figuring this out or reverting this change.

**Closed by niemyjski** 2021-04-15 00:51 UTC
